### ISSUE TITLE
No overload for method 'RequestAttributeValueUpdate' takes 1 arguments	

### ISSUE THREAD

**Issue by djradon** [otopcu/STMS#1]
When I try to build the solution, I get three of these errors:
No overload for method 'RequestAttributeValueUpdate' takes 1 arguments	

StationFdApp	C:\dev\stms\STMS\StationFdApp\StationFdApp.cs	218	
StationFdApp	C:\dev\stms\STMS\StationFdApp\StationFdApp.cs	231
ShipFdApp	C:\dev\stms\STMS\ShipFdApp\ShipFdApp.cs	228

**Comment by otopcu** [comment]
Please use RACoN v0.0.2.4 with STMS branch 0.0.2.4.
